[package]
name = "ntex-h2"
version = "0.3.0"
license = "MIT"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "An HTTP/2 client and server"
documentation = "https://docs.rs/ntex-h2"
repository = "https://github.com/ntex-rs/ntex-h2"
readme = "README.md"
keywords = ["http", "async", "non-blocking"]
categories = ["asynchronous", "web-programming", "network-programming"]
exclude = ["fixtures/**", "util/**", "fuzz/**"]
edition = "2018"

[dependencies]
ntex-connect = "0.3.0"
ntex-io = "0.3.0"
ntex-http = "0.1.8"
ntex-bytes = "0.1.19"
ntex-codec = "0.6.2"
ntex-service = "1.2.0"
ntex-util = "0.3.0"
ntex-rt = "0.4.7"

bitflags = "1.3"
fxhash = "0.2.1"
log = "0.4"
pin-project-lite = "0.2"
thiserror = "1.0"

[dev-dependencies]
# Fuzzing
quickcheck = { version = "1.0.3", default-features = false }
rand = "0.8.4"

# HPACK fixtures
hex = "0.4.3"
walkdir = "2.3.2"
serde = "1.0.0"
serde_json = "1.0.0"

ntex = { version = "0.7.0", features = ["openssl", "tokio"] }
ntex-tls = { version = "0.3.0", features = ["openssl"] }
openssl = "0.10"

# Examples
env_logger = { version = "0.10", default-features = false }
ntex-connect = { version = "0.3.0", features = ["openssl", "tokio"] }

[patch.crates-io]
ntex-h2 = { path = "." }
ntex = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-service = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-util = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-tls = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-io = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-connect = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-tokio = { git = "https://github.com/ntex-rs/ntex.git" }
