[package]
name = "ntex-h2"
version = "0.1.0"
license = "MIT"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "An HTTP/2 client and server (h2 crate fork)"
documentation = "https://docs.rs/ntex-h2"
repository = "https://github.com/ntex-rs/ntex-h2"
readme = "README.md"
keywords = ["http", "async", "non-blocking"]
categories = ["asynchronous", "web-programming", "network-programming"]
exclude = ["fixtures/**", "ci/**"]
edition = "2018"

[workspace]
members = [
    #"tests/h2-fuzz",
    #"tests/h2-tests",
    #"tests/h2-support",
    #"util/genfixture",
    #"util/genhuff",
]

[dependencies]
ntex-connect = "0.1.0"
ntex-io = "0.1.8"
ntex-http = "0.1.0"
ntex-bytes = "0.1.14"
ntex-codec = "0.6.2"
ntex-service = "0.3.1"
ntex-util = "0.1.17"
ntex-rt = "0.4.4"

bitflags = "1.3"
fxhash = "0.2.1"
log = "0.4"
pin-project-lite = "0.2"
thiserror = "1.0"

[dev-dependencies]
# Fuzzing
quickcheck = { version = "1.0.3", default-features = false }
rand = "0.8.4"

# HPACK fixtures
hex = "0.4.3"
walkdir = "2.3.2"
serde = "1.0.0"
serde_json = "1.0.0"

# Examples
env_logger = { version = "0.9", default-features = false }
openssl = "0.10"
ntex = { version = "0.5", features = ["openssl", "tokio"] }
ntex-tls = { version = "0.1", features = ["openssl"] }
ntex-connect = { version = "0.1", features = ["openssl"] }
