[package]
name = "ntex-h2"
version = "0.5.0-b.0"
license = "MIT"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "An HTTP/2 client and server"
documentation = "https://docs.rs/ntex-h2"
repository = "https://github.com/ntex-rs/ntex-h2"
readme = "README.md"
keywords = ["http", "async", "non-blocking"]
categories = ["asynchronous", "web-programming", "network-programming"]
exclude = ["fixtures/**", "util/**", "fuzz/**"]
edition = "2018"

[features]
default = []

# unstable features
unstable = []

[dependencies]
ntex-connect = "1.0.0-b.0"
ntex-io = "1.0.0-b.0"
ntex-http = "0.1.10"
ntex-bytes = "0.1.21"
ntex-codec = "0.6.2"
ntex-service = "2.0.0-b.0"
ntex-util = "1.0.0-b.0"
ntex-rt = "0.4.10"

bitflags = "2.4"
fxhash = "0.2.1"
log = "0.4"
pin-project-lite = "0.2"
thiserror = "1.0"
nanorand = { version = "0.7.0", default-features = false, features = ["std", "wyrand"] }

[dev-dependencies]
# Fuzzing
quickcheck = { version = "1.0.3", default-features = false }
rand = "0.8.4"

# HPACK fixtures
hex = "0.4.3"
walkdir = "2.3.2"
serde = "1.0.0"
serde_json = "1.0.0"

ntex = { version = "1.0.0-b.0", features = ["openssl", "tokio"] }
ntex-tls = { version = "1.0.0-b.0", features = ["openssl"] }
openssl = "0.10"

# Examples
env_logger = { version = "0.10", default-features = false }
ntex-connect = { version = "1.0.0-b.0", features = ["openssl", "tokio"] }

[patch.crates-io]
ntex-h2 = { path = "." }
