[package]
name = "ntex-h2"
version = "0.1.0"
license = "MIT"
authors = [
  "Nikolay Kim <fafhrd91@gmail.com>",
  "Carl Lerche <me@carllerche.com>",
  "Sean McArthur <sean@seanmonstar.com>",
]
description = "An HTTP/2 client and server (h2 crate fork)"
documentation = "https://docs.rs/ntex-h2"
repository = "https://github.com/ntex-rs"
readme = "README.md"
keywords = ["http", "async", "non-blocking"]
categories = ["asynchronous", "web-programming", "network-programming"]
exclude = ["fixtures/**", "ci/**"]
edition = "2018"

[workspace]
members = [
    "tests/h2-fuzz",
    "tests/h2-tests",
    "tests/h2-support",
    "util/genfixture",
    "util/genhuff",
]

[dependencies]
ntex-io = "0.1.8"
ntex-bytes = "0.1.14"
ntex-codec = "0.6.2"

futures-core = { version = "0.3", default-features = false }
futures-sink = { version = "0.3", default-features = false }
futures-util = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["io-util"] }
bytes = "1"
http = "0.2"
tracing = { version = "0.1.21", default-features = false, features = ["std"] }
fnv = "1.0.5"
slab = "0.4.2"
indexmap = { version = "1.5.2", features = ["std"] }
log = "0.4"

[dev-dependencies]
# Fuzzing
quickcheck = { version = "1.0.3", default-features = false }
rand = "0.8.4"

# HPACK fixtures
hex = "0.4.3"
walkdir = "2.3.2"
serde = "1.0.0"
serde_json = "1.0.0"

# Examples
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "net"] }
env_logger = { version = "0.9", default-features = false }
tokio-rustls = "0.23.2"
webpki-roots = "0.22.2"
